spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
    api-docs:
      path: /v3/api-docs
      packages-to-scan: com.psn.catalog.controller

  server:
    port: ${PORT:8080}