spring:
  profiles:
    active: dev  # Perfil ativo por padrão (pode ser sobrescrito)

# Configurações que são comuns a todos os ambientes
app:
  name: PsnCatalog-Maven
  description: Je catálogo de jogos de Playstation