spring:
  config:
    activate-on-profile: prd
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
        format_sql: false
    hibernate:
      ddl-auto: validate
  api-docs:
    path: /v3/api-docs
    packages-to-scan: com.psn.catalog.controller

logging:
  level:
    root: warn
    com.psn.catalog: info