spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
  server:
    port: ${PORT:8080}
    forward-headers-strategy: framework