spring:
  config:
    activate-on-profile: dev
  datasource:
    url: jdbc:h2:mem:psncatalog
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    packages-to-scan: com.psn.catalog.controller
logging:
  level:
    root: info
    org.springframework.web: debug
    com.psn.catalog: debug

